export const ADDBOILERTYPE = 'ADD_BOILER_TYPES';
export const DELETEBOILERTYPE = 'DELETE_BOILER_TYPES';
export const GET_BOILERTYPES_FETCHING = 'GET_BOILERTYPES_FETCHING';
export const GET_BOILERTYPES_FULFILLED = 'GET_BOILERTYPES_FULFILLED';
export const GET_BOILERTYPES_REJECTED = 'GET_BOILERTYPES_REJECTED';
